language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexEntityExtractor
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: EntitySynonymMapper
  - name: DucklingEntityExtractor
    dimensions: ["number", "time"]
    url: "http://localhost:8000"
    timezone: "Asia/Kolkata"
  - name: DIETClassifier
    epochs: 100
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
    max_history: 4
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
